---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
#read data
decathlon <- read_rds('raw_data/decathlon.rds')
library(tibble)
#convert row names to a column named "Name"
decathlon_2 <- tibble::rownames_to_column(decathlon, "Competitor")
#rename columns and clean data
library(janitor)
decathlon_tidy <- decathlon_2 %>% 
  clean_names()

##lower case to all names


# formats check
str(decathlon_tidy)
#1. Who had the longest long jump seen in the data?
decathlon_tidy_01 <- decathlon_tidy %>% 
  slice_max(long_jump, n = 1) %>% 
  select(competitor, long_jump, competition)
#2. What was the average 100m time in each competition?
decathlon_tidy_02 <- decathlon_tidy %>% 
group_by(competition) %>% 
summarise(avg_100_m = mean(x100m))
#3. Who had the highest total points across both competitions?
decathlon_tidy_03 <- decathlon_tidy %>% 
  slice_max(points, n=1) %>% 
  select(competitor, points, competition)
#4. What was the shot-put scores for the top three competitors in each competition?
decathlon_tidy_04 <- decathlon_tidy %>%
  group_by(competition) %>%
  slice_max(shot_put, n=3) %>%
  select(competitor, shot_put, competition)
#5. What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?

less_than_50 <- filter(decathlon_tidy, x400m<50) %>% 
summarise("mean" = mean(points)) %>% 
  add_column(time="<50", .before="mean")
more_than_50 <- filter(decathlon_tidy, x400m>50) %>% 
summarise("mean" = mean(points)) %>% 
  add_column(time=">50", .before="mean")
decathlon_tidy_05 <- full_join(less_than_50, more_than_50)
```
#visualisation: Total Score by competitor by competition
```{r}
plot_1 <- decathlon_tidy %>% 
  select(competitor, points, competition) %>% 
mutate(competitor = tolower(competitor)) %>% 
  arrange(competitor)
ggplot(data = plot_1, aes(fill=competition, x = competitor, y = points)) +
  geom_col(position="dodge", stat="identity") +
  #facet_grid(cols = vars(competition))+
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))
```



#visualisation: 100m Time by competitor by competition
```{r}
plot_2 <- decathlon_tidy %>% 
  select(competitor, x100m, competition) %>% 
mutate(competitor = tolower(competitor)) %>% 
  arrange(competitor)
ggplot(data = plot_2, aes(fill=competition, x = competitor, y = x100m)) +
  geom_col(position="dodge", stat="identity") +
  #facet_grid(cols = vars(competition))+
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))
```


