---
title: "task_02"
output: html_document
date: "2023-03-15"
---

```{r}
library(tidyverse)
cake_1 <- read_csv('raw_data/cake-ingredients-1961.csv')
cake_2 <- read_csv('raw_data/cake_ingredient_code.csv')


cake_tidy_01 <- pivot_longer(cake_1, cols=c(2:35),
             names_to = "code",
values_to = "units", values_drop_na = TRUE)
## join two tables  + a bit of tidying up (remove the "code" column and reorder columns)

cake_tidy_02 <- tibble(inner_join(cake_tidy_01, cake_2, by=join_by("code"))) %>% 
  mutate(code = NULL)
cake_tidy_03 = cake_tidy_02[,c(1,3,2,4)]
write_csv(cake_tidy_03, "clean_data/cake_ingredients.csv")

```
```{r}
cake_tidy_03 %>% 
  filter(ingredient=="Cocoa") %>% 
  slice_max(units, n=1)
```
```{r}
cake_tidy_03 %>% 
  filter(Cake == "Sponge" & measure=="cup") %>% 
  summarise(sum(units)) %>% 
  pull()
```

```{r}
cake_tidy_03 %>% 
  filter(measure=="teaspoon") %>% 
  group_by(ingredient) %>% 
  summarise() %>% 
  nrow()
```

```{r}
cake_tidy_03 %>% 
  group_by(Cake) %>% 
  summarise(unique_in = sum(n_distinct(ingredient))) %>% 
  slice_max(unique_in)
```
```{r}
cake_tidy_03 %>% 
  add_count(ingredient) %>% 
  filter(n == 1) %>% 
  select(ingredient) %>% 
  pull()
```

